### ISSUE TITLE
Docker version is greater than the most recently validated version

### ISSUE THREAD

**Issue by rodrigobrim** [geerlingguy/ansible-role-kubernetes#22] opened 2018-09-28 21:21 UTC
Hello, Jeff.

Now, I receive this error:

```
TASK [geerlingguy.kubernetes : Join node to Kubernetes master] ***********************
fatal: [174.35.241.201]: FAILED! => {"changed": true, "cmd": "kubeadm join 10.0.2.15:6443 --token l7ltia.jve4p1520jmt8yw5 --discovery-token-ca-cert-hash sha256:3c55f99c2710fee05c7b6ef701aeec13902b35d8c245dcc109e015cc0fa03a48", "delta": "0:00:00.169237", "end": "2018-09-28 21:20:16.499901", "msg": "non-zero return code", "rc": 2, "start": "2018-09-28 21:20:16.330664", "stderr": "I0928 21:20:16.374776   24804 kernel_validator.go:81] Validating kernel version\nI0928 21:20:16.374840   24804 kernel_validator.go:96]Validating kernel config\n\t[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 18.06.1-ce. Max validated version: 17.03\n[preflight] Some fatal errors occurred:\n\t[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "stderr_lines": ["I0928 21:20:16.374776   24804 kernel_validator.go:81] Validating kernel version", "I0928 21:20:16.374840   24804 kernel_validator.go:96] Validating kernel config", "\t[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 18.06.1-ce. Max validated version: 17.03", "[preflight] Some fatal errors occurred:", "\t[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`"], "stdout": "[preflight] running pre-flight checks", "stdout_lines": ["[preflight] running pre-flight checks"]}
        to retry, use: --limit @/home/ansible/projects/lab-kubernetes/playbook.retry

```

Thank you

**Comment by geerlingguy** [comment] 2018-09-29 01:07
It looks like the main error in that big list is:

```
/proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
```

Do you have a full playbook you can provide that can reproduce this problem? The test playbooks running in this project's CI seem to be installing successfully even with the latest version of Docker.

**Comment by rodrigobrim** [comment] 2018-09-29 02:10
Hello, Jeff.

This is here:

`[ansible@ansible-server lab-kubernetes]$ cat inventory
[all]
174.35.241.200 kubernetes_role="master"
174.35.241.201 kubernetes_role="node"
174.35.241.202 kubernetes_role="node"
174.35.241.203 kubernetes_role="node"
[ansible@ansible-server lab-kubernetes]$ cat playbook.yml
- hosts: all
  become: yes

  vars:
    kubernetes_allow_pods_on_master: True
    kubernetes_pod_network_cidr: 10.244.0.0/16

  roles:
    - brim.swapoff
    - geerlingguy.docker
    - geerlingguy.kubernetes
[ansible@ansible-server lab-kubernetes]$
`

**Comment by rodrigobrim** [comment] 2018-09-29 02:13
My role - copylefted from a source that I don't remember :D

```[ansible@ansible-server lab-kubernetes]$ find ../../.ansible/roles/brim.swapoff
../../.ansible/roles/brim.swapoff
../../.ansible/roles/brim.swapoff/tasks
../../.ansible/roles/brim.swapoff/tasks/main.yml
[ansible@ansible-server lab-kubernetes]$ cat ../../.ansible/roles/brim.swapoff/tasks/main.yml
---
# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
[ansible@ansible-server lab-kubernetes]$```

**Comment by geerlingguy** [comment] 2018-09-29 19:45
Interesting, that _should_ work with the latest version of this role (which I just updated this weekend).

Are you using VirtualBox VMs? If so, your base box might not have the right settings—see: https://github.com/kubernetes/kubeadm/issues/312#issuecomment-309539056

I am using my `geerlingguy/debian9` base box for the Raspberry Pi cluster testing in VirtualBox and don't seem to have this issue.

**Comment by rodrigobrim** [comment] 2018-09-29 20:14
Hello, Jeff.

I'm using Virtualbox with geerlingguy/centos7.

I can't post my playbook now. Until monday, I'll post it.




Em sáb, 29 de set de 2018 16:45, Jeff Geerling <notifications@github.com>
escreveu:

**Comment by geerlingguy** [comment] 2019-03-31 03:34
Closing this for now—but note that I'm also seeing some strange issues with the Ubuntu 18.04 and Debian 9 test environments for this role; follow #42 for progress.

**Closed by geerlingguy** 2019-03-31 03:34 UTC
