### ISSUE TITLE
Fail when deploying flannel

### ISSUE THREAD

**Issue by rodrigobrim** [geerlingguy/ansible-role-kubernetes#20] opened 2018-09-22 23:02 UTC
Hello Jeff. Here is the problem:

```
TASK [geerlingguy.kubernetes : Configure Flannel networking.] **************************************************************************************************************
failed: [174.35.241.200] (item=kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml) => {"changed": fa
lse, "cmd": ["kubectl", "apply", "-f", "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml"], "delta": "0:00:00.36889
2", "end": "2018-09-22 22:57:48.898430", "item": "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
", "msg": "non-zero return code", "rc": 1, "start": "2018-09-22 22:57:48.529538", "stderr": "unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/D
ocumentation/k8s-manifests/kube-flannel-rbac.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused\nunable to recognize \"
https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:
6443: connect: connection refused", "stderr_lines": ["unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel
-rbac.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused", "unable to recognize \"https://raw.githubusercontent.com/cor
eos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused"],
"stdout": "", "stdout_lines": []}
failed: [174.35.241.200] (item=kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml) => {"changed": false, "cmd": ["kubec
tl", "apply", "-f", "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"], "delta": "0:00:00.345040", "end": "2018-09-22 22:57:49.614758
", "item": "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml", "msg": "non-zero return code", "rc": 1, "start": "2018
-09-22 22:57:49.269718", "stderr": "unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:64
43/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused\nunable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-f
lannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused\nunable to recognize \"https://raw.githubusercontent.com/core
os/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused\nunable to recognize \"
https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: conn
ection refused\nunable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s:
dial tcp 10.0.2.15:6443: connect: connection refused\nunable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get ht
tps://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused\nunable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Do
cumentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused\nunable to recognize \"https://raw.githubus
ercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused\nunab
le to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6
443: connect: connection refused", "stderr_lines": ["unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get htt
ps://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused", "unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/D
ocumentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused", "unable to recognize \"https://raw.githu
busercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused",
"unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2
.15:6443: connect: connection refused", "unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.
15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused", "unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation
/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused", "unable to recognize \"https://raw.githubusercontent
.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused", "unable to r
ecognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?timeout=32s: dial tcp 10.0.2.15:6443: co
nnect: connection refused", "unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml\": Get https://10.0.2.15:6443/api?
timeout=32s: dial tcp 10.0.2.15:6443: connect: connection refused"], "stdout": "", "stdout_lines": []}
```

Deployed on:

```
[ansible@ansible-server lab-kubernetes]$ ssh 174.35.241.200
Last login: Sat Sep 22 22:57:49 2018 from 174.35.241.10
[ansible@k8s-node2 ~]$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
[ansible@k8s-node2 ~]$ uname -a
Linux k8s-node2 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[ansible@k8s-node2 ~]$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/version: dial unix /var/run/docker.sock: connect: permission denied
[ansible@k8s-node2 ~]$
```

Can you help me?

**Comment by rodrigobrim** [comment] 2018-09-22 23:03
[ansible@ansible-server lab-kubernetes]$ cat playbook.yml
- hosts: all
  become: yes

  vars:
    kubernetes_allow_pods_on_master: True

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
[ansible@ansible-server lab-kubernetes]$ cat inventory
[all]
174.35.241.200 kubernetes_role="master"
174.35.241.201 kubernetes_role="node"
174.35.241.202 kubernetes_role="node"
174.35.241.203 kubernetes_role="node"
[ansible@ansible-server lab-kubernetes]$

**Comment by geerlingguy** [comment] 2018-09-23 17:01
Can you reset the servers and try setting:

```
kubernetes_pod_network_cidr: 10.244.0.0/16
```

If that fixes it, I should probably just update the default.

**Comment by geerlingguy** [comment] 2018-09-23 17:01
(And see related: https://github.com/geerlingguy/ansible-role-kubernetes/issues/17)

**Comment by rodrigobrim** [comment] 2018-09-23 17:31
I'll try, and post the results.

Thank you.

Em dom, 23 de set de 2018 14:01, Jeff Geerling <notifications@github.com>
escreveu:

**Comment by geerlingguy** [comment] 2018-09-28 03:43
See: https://github.com/coreos/flannel/issues/1044

**Comment by geerlingguy** [comment] 2018-09-28 03:54
Also see related: #18.

**Comment by geerlingguy** [comment] 2018-09-28 04:29
This has been fixed by setting the CIDR correctly, and by pinning the Kubernetes version to 1.11 (due to the flannel bug mentioned two comments above).

**Closed by geerlingguy** 2018-09-28 04:29 UTC

**Comment by stephenwithav** [comment] 2018-11-27 20:40
@geerlingguy I'm getting the same error on Debian stretch using the 10.244.0.0/16 subnet:

```
sudo kubectl apply -f https://raw.githubusercontent.com/coreo
s/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml": Get https://10.0.2.15:6443/api?timeout=32s:
 dial tcp 10.0.2.15:6443: connect: connection refused
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml": Get https://10.0.2.15:6443/api?timeout=32s:
 dial tcp 10.0.2.15:6443: connect: connection refused
```

I'm running k8s 1.11.5.

**Comment by papanito** [comment] 2018-12-01 11:37
I am running into the same issue as well on Debian stretch 
```
Linux Debian-95-stretch-64-minimal 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
```
I am using
```
geerlingguy.kubernetes, 2.0.0
```

**Comment by geerlingguy** [comment] 2018-12-01 19:50
I wonder if the Flannel default config has changed recently. It used to work fine with 1.10 and 1.11 but have issues with 1.12. Maybe it's the inverse now?

I will be dipping back into this role again soon, so should have more time for debugging then. Right now I'm in the middle of a lot of pre-new-year work that is holding up my ability to work on some of my roles.

**Comment by geerlingguy** [comment] 2018-12-01 19:51
Also, it might be good to try opening a new issue with all the details of your issue (e.g. error logs, messages, steps to reproduce, etc.).

**Comment by linbingdouzhe** [comment] 2019-08-12 07:47
i got the same issue about this.....
i got that error when i configure flaneeling networking 

Get https://192.168.17.40:6443/api?timeout=32s: dial tcp 192.168.17.40:6443: connect: connection refused"], "stdout": "", "stdout_lines": []}

i am trying to change kubernetes version ,from 1.15.0 => 1.11.0
